sudo: required
services:
  - docker

before_install:
  - docker build -t levpa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true levpa/react-test npm test -- --coverage

after_success:
  - docker build -t levpa/multi-client ./client
  - docker build -t levpa/multi-nginx ./nginx
  - docker build -t levpa/multi-server ./server
  - docker build -t levpa/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push levpa/multi-client
  - docker push levpa/multi-nginx
  - docker push levpa/multi-server
  - docker push levpa/multi-worker
  # Deploy to the AWS BeansTalk
  deploy:
    provider: elasticbeanstalk
    region: 'eu-central-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-eu-central-1-062423807195'
    bucket_path: 'docker-multi'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    